"""Export ESP32 TinyML model bundle (.joblib) to a C header for firmware inference.

Usage:
  python models/export_esp32_header.py \
    --input models/sound_classifier_esp32.joblib \
    --output ../Node/include/tinyml_model_params.h
"""

from __future__ import annotations

import argparse
from pathlib import Path

import joblib
import numpy as np


def _format_float_array(name: str, values: np.ndarray, line_values: int = 8) -> str:
    flat = np.asarray(values, dtype=np.float32).reshape(-1)
    chunks: list[str] = []
    for i in range(0, len(flat), line_values):
        row = ", ".join(f"{v:.9g}f" for v in flat[i : i + line_values])
        chunks.append(f"    {row}")
    body = ",\n".join(chunks)
    return f"static const float {name}[{len(flat)}] = {{\n{body}\n}};\n"


def _class_name_array(classes: dict[int, str]) -> str:
    ordered = [classes[i] if i in classes else f"class_{i}" for i in range(max(classes.keys()) + 1)]
    lines = [f'    "{label}"' for label in ordered]
    return (
        f"static const char* const kTinyMlClassNames[{len(ordered)}] = {{\n"
        + ",\n".join(lines)
        + "\n};\n"
    )


def build_header(model: dict) -> str:
    weights = model["weights"]
    biases = model["biases"]
    mean = np.asarray(model["mean"], dtype=np.float32).reshape(-1)
    std = np.asarray(model["std"], dtype=np.float32).reshape(-1)

    w_shapes = [np.asarray(w).shape for w in weights]
    b_shapes = [np.asarray(b).shape for b in biases]

    if len(weights) != 3 or len(biases) != 3:
        raise ValueError(f"Expected 3-layer MLP bundle, got weights={len(weights)} biases={len(biases)}")

    in_dim = int(w_shapes[0][0])
    h1_dim = int(w_shapes[0][1])
    h2_dim = int(w_shapes[1][1])
    out_dim = int(w_shapes[2][1])

    if w_shapes[1][0] != h1_dim or w_shapes[2][0] != h2_dim:
        raise ValueError(f"Incompatible layer shapes: {w_shapes}")

    if len(mean) != in_dim or len(std) != in_dim:
        raise ValueError(f"Scaler dim mismatch: mean/std={len(mean)} expected={in_dim}")

    b0 = np.asarray(biases[0], dtype=np.float32).reshape(-1)
    b1 = np.asarray(biases[1], dtype=np.float32).reshape(-1)
    b2 = np.asarray(biases[2], dtype=np.float32).reshape(-1)

    if len(b0) != h1_dim or len(b1) != h2_dim or len(b2) != out_dim:
        raise ValueError("Bias dims do not match weight dims")

    classes = {int(k): str(v) for k, v in dict(model.get("classes", {})).items()}

    header_parts = [
        "#ifndef TINYML_MODEL_PARAMS_H",
        "#define TINYML_MODEL_PARAMS_H",
        "",
        "// Auto-generated by Simulation/models/export_esp32_header.py",
        "// Do not edit manually.",
        "",
        "static const int kTinyMlInputDim = %d;" % in_dim,
        "static const int kTinyMlHidden1Dim = %d;" % h1_dim,
        "static const int kTinyMlHidden2Dim = %d;" % h2_dim,
        "static const int kTinyMlOutputDim = %d;" % out_dim,
        "",
        _format_float_array("kTinyMlMean", mean),
        _format_float_array("kTinyMlStd", std),
        _format_float_array("kTinyMlW1", np.asarray(weights[0], dtype=np.float32).reshape(-1)),
        _format_float_array("kTinyMlB1", b0),
        _format_float_array("kTinyMlW2", np.asarray(weights[1], dtype=np.float32).reshape(-1)),
        _format_float_array("kTinyMlB2", b1),
        _format_float_array("kTinyMlW3", np.asarray(weights[2], dtype=np.float32).reshape(-1)),
        _format_float_array("kTinyMlB3", b2),
        _class_name_array(classes),
        "#endif  // TINYML_MODEL_PARAMS_H",
        "",
    ]
    return "\n".join(header_parts)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export TinyML joblib bundle to C header")
    parser.add_argument("--input", required=True, help="Input .joblib model bundle")
    parser.add_argument("--output", required=True, help="Output .h file path")
    args = parser.parse_args()

    model_path = Path(args.input)
    output_path = Path(args.output)

    model = joblib.load(model_path)
    if not isinstance(model, dict):
        raise TypeError("Model bundle must be a dict")

    header = build_header(model)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header, encoding="utf-8")

    print(f"Exported TinyML header: {output_path}")
    print(f"Input model: {model_path}")


if __name__ == "__main__":
    main()
